"""Deterministic provider compatibility matrix generation."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from .client import PROVIDER_SPECS, validate_provider_registry


def build_matrix(fixture_root: Path) -> dict[str, object]:
    registry_errors = validate_provider_registry()
    if registry_errors:
        raise ValueError("; ".join(registry_errors))
    rows = []
    for name, spec in PROVIDER_SPECS.items():
        fixture_path = fixture_root / spec.fixture
        if not fixture_path.is_file():
            raise ValueError(f"missing fixture for {name}: {fixture_path}")
        fixture_bytes = fixture_path.read_bytes()
        payload = json.loads(fixture_bytes)
        if payload.get("provider") != name or not isinstance(payload.get("expected"), dict):
            raise ValueError(f"fixture identity/expected contract mismatch for {name}")
        rows.append(
            {
                "provider": name,
                "transport": spec.transport,
                "sdk": spec.sdk,
                "maintainer": spec.maintainer,
                "fixture": f"tests/fixtures/providers/{spec.fixture}",
                "fixture_sha256": hashlib.sha256(fixture_bytes).hexdigest(),
                "contract": {
                    "text": "normalized",
                    "usage": "nullable-token-fields",
                    "timeout": "bounded",
                    "retry": "central-policy",
                    "errors": "normalized",
                    "lifecycle": "explicit-close",
                },
                "status": "recorded-contract",
            }
        )
    return {
        "schema_version": 1,
        "generator": "scripts/generate_provider_matrix.py",
        "providers": rows,
    }


def render_markdown(matrix: dict[str, object]) -> str:
    lines = [
        "<!-- Generated by scripts/generate_provider_matrix.py; do not edit manually. -->",
        "# Provider Compatibility Matrix",
        "",
        "Every row is derived from the provider registry and a recorded fixture exercised by the shared contract suite. `recorded-contract` proves deterministic adapter behavior, not live vendor availability or model quality.",
        "",
        "| Provider | Transport | SDK | Maintainer | Contract | Fixture SHA-256 |",
        "|---|---|---|---|---|---|",
    ]
    for row in matrix["providers"]:
        lines.append(
            "| {provider} | {transport} | {sdk} | @{maintainer} | {status} | `{digest}` |".format(
                provider=row["provider"],
                transport=row["transport"],
                sdk=row["sdk"],
                maintainer=row["maintainer"],
                status=row["status"],
                digest=row["fixture_sha256"],
            )
        )
    lines.extend(
        [
            "",
            "Regenerate with:",
            "",
            "```bash",
            "python scripts/generate_provider_matrix.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def json_text(matrix: dict[str, object]) -> str:
    return json.dumps(matrix, indent=2, sort_keys=True) + "\n"
